name: Browser Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  JUPYTER_TEST_BROWSER: firefox
  MOZ_HEADLESS: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: ['3.6', '3.8', '3.9']
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cache conda
      uses: actions/cache@v1
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ hashFiles('.github/tests-browser.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-${{ matrix.python-version }}-
    - name: Install Browser Test Dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: .github/tests-browser.yml
    - name: List conda packages
      run: |
        conda list --explicit
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          ${{ runner.os }}-pip-
    - name: Build static assets
      run: |
        python setup.py build
    - name: Install the Python dependencies
      run: |
        pip install -e .[test] codecov
    - name: List installed packages
      run: |
        pip freeze
        pip check
    - name: Run selenium tests
      timeout-minutes: 30
      run: |
        py.test -sv notebook/tests/selenium ${{ matrix.selenium-pytest-args }}
    - name: Install npm dependencies
      run: |
        npm install -g casperjs@1.1.3 phantomjs-prebuilt@2.1.7
    - name: Run legacy js tests
      timeout-minutes: 30
      run: |
        python -m notebook.jstest
